import { buildEvent } from './buildEvent';
import type { PlaybookCategory } from './types';

export const globalGatherings: PlaybookCategory = {
  id: 'global-gatherings',
  titleTr: 'Topluluk baglayicilari (Global Gatherings)',
  titleEn: 'Community Connectors / Global Gatherings',
  description:
    'Cesitlilik ve kulturel etkilesim; Molada kapasite ve mekan ici odak. Dis mekan BBQ yoksa ic alternatif plani.',
  events: [
    buildEvent(
      'movie-night',
      'Movie Night',
      'Film gecesi',
      'Rahat, sosyal izleme.',
      'Projeksiyon; telif ve ses; komsu saati.',
      ['Film oylamasi; yas siniri.', 'Ikram ve alerjen afisi.'],
      ['Koltuk, isik, altyazi; ara mola.', 'Telif riski kontrolu.'],
    ),
    buildEvent(
      'board-game-night',
      'Board Game Night',
      'Masa oyunu gecesi',
      'Tanisma ve dusuk riskli rekabet.',
      'Masa sayisi ve oyun deposu.',
      ['Kural ozet kartlari; masa atamasi.', 'Sessiz odak saatiyle cakisma kontrolu.'],
      ['Ilk turda anlatim; foto izni.'],
    ),
    buildEvent(
      'mafia-night',
      'Mafia Game Night',
      'Mafia oyunu gecesi',
      'Sosyal cikarim eglencesi.',
      'Cok oyuncu: iki oda ve moderasyon.',
      ['Moderator ve kural özeti PDF.', 'Tur sure limiti.'],
      ['Dis uye daveti uyelik kurallarina uygun.', 'Video cekim politikasi.'],
    ),
    buildEvent(
      'summer-bbq',
      'Summer BBQs',
      'Yaz bulusmasi / mangal alternatifi',
      'Disarda veya ic mekan piknik temasi.',
      'Mangal yoksa catering tabak; dumana izin araştirmasi.',
      ['Hava icin yedek ic tarih.', 'Vejetaryen secenekleri. Hijyen.'],
      ['Tek kullanimlik politikas; cop ayristirma.'],
    ),
    buildEvent(
      'bowling-night',
      'Bowling Nights',
      'Bowling (dis mekan)',
      'Salonda grup etkinligi.',
      'Toplu ulasim veya bulusma saati.',
      ['Salon rezervasyonu; ayakkabi.', 'Katilim ucreti seffafligi.'],
      ['Donus ulasimi hatirlatici.', 'Grup fotografi izni.'],
    ),
    buildEvent(
      'pet-day',
      'Bring Your Pet to Work Day',
      'Evcil hayvan gunu',
      'Pet-friendly deneyim; risk kontrollu.',
      'Sozlesmede hayvan politikasi; alerji duyurusu zorunlu.',
      ['Tasma/asi kurallari; pet-free alan.', 'Temizlik kiti ve dis yuruyus rotasi.'],
      ['Acik riza fotograf; hassas uyeler icin uyari.'],
    ),
    buildEvent(
      'book-club',
      'Book Club',
      'Kitap kulubu',
      'Ortak okuma ve tartisma.',
      'Sessiz kose veya toplanti odasi.',
      ['Kitap oylamasi; sayfa hedefi.', 'Moderator sorulari; spoiler kurali.'],
      ['Sonraki kitap oneri kutusu.'],
    ),
    buildEvent(
      'language-clubs',
      'Language Speaking Clubs',
      'Dil konusma kulubu',
      'Dil pratigi ve degisim.',
      'Gurultu: kucuk grup veya kabin rotasyonu.',
      ['Seviye gruplari; materyal paylasimi.', 'Hibrit icin tek kulaklik kosesi.'],
      ['Kulturel saygi kurallari.'],
    ),
    buildEvent(
      'international-cuisine',
      'International Cuisine Day',
      'Uluslararasi mutfak gunu',
      'Potluck ve cesitlilik.',
      'Buzdolabi ve isitma; alerjen etiket.',
      ['Hijyen brosuru.', 'Yikama veya tek kullanim plani.'],
      ['Paylasim sirasi; cop ayristirma.'],
    ),
    buildEvent(
      'cultural-workshops',
      'Cultural Workshops',
      'Kulturel atolye',
      'Gelenek paylasimi.',
      'Malzeme depolama; duygusal yuklu konularda moderator.',
      ['Konu ve sinirlar onceden yazili.', 'Malzeme listesi paylasimi.'],
      ['Hikaye suresi siniri; saygi.'],
    ),
  ],
};
